// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Author: typeof import('./src/components/Author.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    Date: typeof import('./src/components/Date.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    LocaleSwitcher: typeof import('./src/components/LocaleSwitcher.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MobileMenu: typeof import('./src/components/MobileMenu.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostItem: typeof import('./src/components/PostItem.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SectionContainer: typeof import('./src/components/SectionContainer.vue')['default']
    SocialIcon: typeof import('./src/components/SocialIcon.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
  }
}
