/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./src/components/Author.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    Date: typeof import('./src/components/Date.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    LocaleSwitcher: typeof import('./src/components/LocaleSwitcher.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MobileMenu: typeof import('./src/components/MobileMenu.vue')['default']
    PageBreadcrumb: typeof import('./src/components/PageBreadcrumb.vue')['default']
    PageBreadcrumbItem: typeof import('./src/components/PageBreadcrumbItem.vue')['default']
    PageSubtitle: typeof import('./src/components/PageSubtitle.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostItem: typeof import('./src/components/PostItem.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    ProjectSearch: typeof import('./src/components/ProjectSearch.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SectionContainer: typeof import('./src/components/SectionContainer.vue')['default']
    SocialIcon: typeof import('./src/components/SocialIcon.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    Technology: typeof import('./src/components/Technology.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Toc: typeof import('./src/components/Toc.vue')['default']
    TocItem: typeof import('./src/components/TocItem.vue')['default']
    TwBadge: typeof import('./src/components/TwBadge.vue')['default']
    TwDismissableBadge: typeof import('./src/components/TwDismissableBadge.vue')['default']
  }
}
