[build.environment]
  # bypass npm auto install
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"
  YARN_VERSION = "3.2.2"

[build]
  publish = "dist"
  command = "yarn run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*.rss"
  [headers.values]
    Content-Type = "application/rss+xml; charset=utf-8"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [".yarn/cache"]
