[build.environment]
  # bypass npm auto install
  NPM_FLAGS = "--prefix=/dev/null --version"
  NODE_VERSION = "16"
  # YARN_VERSION = "3.2.2"
  VITE_BASE_URL = "https://ansidev.xyz"

[build]
  publish = "dist"
  command = "touch public/{sitemap.xml,robots.txt,feed.rss} && pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*.rss"
  [headers.values]
    Content-Type = "application/rss+xml; charset=utf-8"
