const defaultTheme = require('tailwindcss/defaultTheme')
const colors = require('tailwindcss/colors')

module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,md}",
  ],
  darkMode: 'class',
  safelist: [
    'prose',
    'prose-sm',
    'bg-black',
    'bg-blue-100',
    'bg-blue-200',
    'bg-blue-300',
    'bg-blue-400',
    'bg-blue-500',
    'bg-blue-600',
    'bg-blue-700',
    'bg-blue-800',
    'bg-blue-900',
    'bg-current',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'bg-gray-500',
    'bg-gray-600',
    'bg-gray-700',
    'bg-gray-800',
    'bg-gray-900',
    'bg-green-100',
    'bg-green-200',
    'bg-green-300',
    'bg-green-400',
    'bg-green-500',
    'bg-green-600',
    'bg-green-700',
    'bg-green-800',
    'bg-green-900',
    'bg-indigo-100',
    'bg-indigo-200',
    'bg-indigo-300',
    'bg-indigo-400',
    'bg-indigo-500',
    'bg-indigo-600',
    'bg-indigo-700',
    'bg-indigo-800',
    'bg-indigo-900',
    'bg-orange-100',
    'bg-orange-200',
    'bg-orange-300',
    'bg-orange-400',
    'bg-orange-500',
    'bg-orange-600',
    'bg-orange-700',
    'bg-orange-800',
    'bg-orange-900',
    'bg-pink-100',
    'bg-pink-200',
    'bg-pink-300',
    'bg-pink-400',
    'bg-pink-500',
    'bg-pink-600',
    'bg-pink-700',
    'bg-pink-800',
    'bg-pink-900',
    'bg-purple-100',
    'bg-purple-200',
    'bg-purple-300',
    'bg-purple-400',
    'bg-purple-500',
    'bg-purple-600',
    'bg-purple-700',
    'bg-purple-800',
    'bg-purple-900',
    'bg-red-100',
    'bg-red-200',
    'bg-red-300',
    'bg-red-400',
    'bg-red-500',
    'bg-red-600',
    'bg-red-700',
    'bg-red-800',
    'bg-red-900',
    'bg-teal-100',
    'bg-teal-200',
    'bg-teal-300',
    'bg-teal-400',
    'bg-teal-500',
    'bg-teal-600',
    'bg-teal-700',
    'bg-teal-800',
    'bg-teal-900',
    'bg-transparent',
    'bg-white',
    'bg-yellow-100',
    'bg-yellow-200',
    'bg-yellow-300',
    'bg-yellow-400',
    'bg-yellow-500',
    'bg-yellow-600',
    'bg-yellow-700',
    'bg-yellow-800',
    'bg-yellow-900',
    'dark:bg-black',
    'dark:bg-blue-100',
    'dark:bg-blue-200',
    'dark:bg-blue-300',
    'dark:bg-blue-400',
    'dark:bg-blue-500',
    'dark:bg-blue-600',
    'dark:bg-blue-700',
    'dark:bg-blue-800',
    'dark:bg-blue-900',
    'dark:bg-current',
    'dark:bg-gray-100',
    'dark:bg-gray-200',
    'dark:bg-gray-300',
    'dark:bg-gray-400',
    'dark:bg-gray-500',
    'dark:bg-gray-600',
    'dark:bg-gray-700',
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:bg-green-100',
    'dark:bg-green-200',
    'dark:bg-green-300',
    'dark:bg-green-400',
    'dark:bg-green-500',
    'dark:bg-green-600',
    'dark:bg-green-700',
    'dark:bg-green-800',
    'dark:bg-green-900',
    'dark:bg-indigo-100',
    'dark:bg-indigo-200',
    'dark:bg-indigo-300',
    'dark:bg-indigo-400',
    'dark:bg-indigo-500',
    'dark:bg-indigo-600',
    'dark:bg-indigo-700',
    'dark:bg-indigo-800',
    'dark:bg-indigo-900',
    'dark:bg-orange-100',
    'dark:bg-orange-200',
    'dark:bg-orange-300',
    'dark:bg-orange-400',
    'dark:bg-orange-500',
    'dark:bg-orange-600',
    'dark:bg-orange-700',
    'dark:bg-orange-800',
    'dark:bg-orange-900',
    'dark:bg-pink-100',
    'dark:bg-pink-200',
    'dark:bg-pink-300',
    'dark:bg-pink-400',
    'dark:bg-pink-500',
    'dark:bg-pink-600',
    'dark:bg-pink-700',
    'dark:bg-pink-800',
    'dark:bg-pink-900',
    'dark:bg-purple-100',
    'dark:bg-purple-200',
    'dark:bg-purple-300',
    'dark:bg-purple-400',
    'dark:bg-purple-500',
    'dark:bg-purple-600',
    'dark:bg-purple-700',
    'dark:bg-purple-800',
    'dark:bg-purple-900',
    'dark:bg-red-100',
    'dark:bg-red-200',
    'dark:bg-red-300',
    'dark:bg-red-400',
    'dark:bg-red-500',
    'dark:bg-red-600',
    'dark:bg-red-700',
    'dark:bg-red-800',
    'dark:bg-red-900',
    'dark:bg-teal-100',
    'dark:bg-teal-200',
    'dark:bg-teal-300',
    'dark:bg-teal-400',
    'dark:bg-teal-500',
    'dark:bg-teal-600',
    'dark:bg-teal-700',
    'dark:bg-teal-800',
    'dark:bg-teal-900',
    'dark:bg-transparent',
    'dark:bg-white',
    'dark:bg-yellow-100',
    'dark:bg-yellow-200',
    'dark:bg-yellow-300',
    'dark:bg-yellow-400',
    'dark:bg-yellow-500',
    'dark:bg-yellow-600',
    'dark:bg-yellow-700',
    'dark:bg-yellow-800',
    'dark:bg-yellow-900',
    'dark:hover:bg-black',
    'dark:hover:bg-blue-100',
    'dark:hover:bg-blue-200',
    'dark:hover:bg-blue-300',
    'dark:hover:bg-blue-400',
    'dark:hover:bg-blue-500',
    'dark:hover:bg-blue-600',
    'dark:hover:bg-blue-700',
    'dark:hover:bg-blue-800',
    'dark:hover:bg-blue-900',
    'dark:hover:bg-current',
    'dark:hover:bg-gray-100',
    'dark:hover:bg-gray-200',
    'dark:hover:bg-gray-300',
    'dark:hover:bg-gray-400',
    'dark:hover:bg-gray-500',
    'dark:hover:bg-gray-600',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-gray-800',
    'dark:hover:bg-gray-900',
    'dark:hover:bg-green-100',
    'dark:hover:bg-green-200',
    'dark:hover:bg-green-300',
    'dark:hover:bg-green-400',
    'dark:hover:bg-green-500',
    'dark:hover:bg-green-600',
    'dark:hover:bg-green-700',
    'dark:hover:bg-green-800',
    'dark:hover:bg-green-900',
    'dark:hover:bg-indigo-100',
    'dark:hover:bg-indigo-200',
    'dark:hover:bg-indigo-300',
    'dark:hover:bg-indigo-400',
    'dark:hover:bg-indigo-500',
    'dark:hover:bg-indigo-600',
    'dark:hover:bg-indigo-700',
    'dark:hover:bg-indigo-800',
    'dark:hover:bg-indigo-900',
    'dark:hover:bg-orange-100',
    'dark:hover:bg-orange-200',
    'dark:hover:bg-orange-300',
    'dark:hover:bg-orange-400',
    'dark:hover:bg-orange-500',
    'dark:hover:bg-orange-600',
    'dark:hover:bg-orange-700',
    'dark:hover:bg-orange-800',
    'dark:hover:bg-orange-900',
    'dark:hover:bg-pink-100',
    'dark:hover:bg-pink-200',
    'dark:hover:bg-pink-300',
    'dark:hover:bg-pink-400',
    'dark:hover:bg-pink-500',
    'dark:hover:bg-pink-600',
    'dark:hover:bg-pink-700',
    'dark:hover:bg-pink-800',
    'dark:hover:bg-pink-900',
    'dark:hover:bg-purple-100',
    'dark:hover:bg-purple-200',
    'dark:hover:bg-purple-300',
    'dark:hover:bg-purple-400',
    'dark:hover:bg-purple-500',
    'dark:hover:bg-purple-600',
    'dark:hover:bg-purple-700',
    'dark:hover:bg-purple-800',
    'dark:hover:bg-purple-900',
    'dark:hover:bg-red-100',
    'dark:hover:bg-red-200',
    'dark:hover:bg-red-300',
    'dark:hover:bg-red-400',
    'dark:hover:bg-red-500',
    'dark:hover:bg-red-600',
    'dark:hover:bg-red-700',
    'dark:hover:bg-red-800',
    'dark:hover:bg-red-900',
    'dark:hover:bg-teal-100',
    'dark:hover:bg-teal-200',
    'dark:hover:bg-teal-300',
    'dark:hover:bg-teal-400',
    'dark:hover:bg-teal-500',
    'dark:hover:bg-teal-600',
    'dark:hover:bg-teal-700',
    'dark:hover:bg-teal-800',
    'dark:hover:bg-teal-900',
    'dark:hover:bg-transparent',
    'dark:hover:bg-white',
    'dark:hover:bg-yellow-100',
    'dark:hover:bg-yellow-200',
    'dark:hover:bg-yellow-300',
    'dark:hover:bg-yellow-400',
    'dark:hover:bg-yellow-500',
    'dark:hover:bg-yellow-600',
    'dark:hover:bg-yellow-700',
    'dark:hover:bg-yellow-800',
    'dark:hover:bg-yellow-900',
    'dark:hover:text-black',
    'dark:hover:text-blue-100',
    'dark:hover:text-blue-200',
    'dark:hover:text-blue-300',
    'dark:hover:text-blue-400',
    'dark:hover:text-blue-50',
    'dark:hover:text-blue-500',
    'dark:hover:text-blue-600',
    'dark:hover:text-blue-700',
    'dark:hover:text-blue-800',
    'dark:hover:text-blue-900',
    'dark:hover:text-current',
    'dark:hover:text-gray-100',
    'dark:hover:text-gray-200',
    'dark:hover:text-gray-300',
    'dark:hover:text-gray-400',
    'dark:hover:text-gray-50',
    'dark:hover:text-gray-500',
    'dark:hover:text-gray-600',
    'dark:hover:text-gray-700',
    'dark:hover:text-gray-800',
    'dark:hover:text-gray-900',
    'dark:hover:text-green-100',
    'dark:hover:text-green-200',
    'dark:hover:text-green-300',
    'dark:hover:text-green-400',
    'dark:hover:text-green-50',
    'dark:hover:text-green-500',
    'dark:hover:text-green-600',
    'dark:hover:text-green-700',
    'dark:hover:text-green-800',
    'dark:hover:text-green-900',
    'dark:hover:text-indigo-100',
    'dark:hover:text-indigo-200',
    'dark:hover:text-indigo-300',
    'dark:hover:text-indigo-400',
    'dark:hover:text-indigo-50',
    'dark:hover:text-indigo-500',
    'dark:hover:text-indigo-600',
    'dark:hover:text-indigo-700',
    'dark:hover:text-indigo-800',
    'dark:hover:text-indigo-900',
    'dark:hover:text-opacity-10',
    'dark:hover:text-orange-100',
    'dark:hover:text-orange-200',
    'dark:hover:text-orange-300',
    'dark:hover:text-orange-400',
    'dark:hover:text-orange-500',
    'dark:hover:text-orange-600',
    'dark:hover:text-orange-700',
    'dark:hover:text-orange-800',
    'dark:hover:text-orange-900',
    'dark:hover:text-pink-100',
    'dark:hover:text-pink-200',
    'dark:hover:text-pink-300',
    'dark:hover:text-pink-400',
    'dark:hover:text-pink-50',
    'dark:hover:text-pink-500',
    'dark:hover:text-pink-600',
    'dark:hover:text-pink-700',
    'dark:hover:text-pink-800',
    'dark:hover:text-pink-900',
    'dark:hover:text-purple-100',
    'dark:hover:text-purple-200',
    'dark:hover:text-purple-300',
    'dark:hover:text-purple-400',
    'dark:hover:text-purple-50',
    'dark:hover:text-purple-500',
    'dark:hover:text-purple-600',
    'dark:hover:text-purple-700',
    'dark:hover:text-purple-800',
    'dark:hover:text-purple-900',
    'dark:hover:text-red-100',
    'dark:hover:text-red-200',
    'dark:hover:text-red-300',
    'dark:hover:text-red-400',
    'dark:hover:text-red-50',
    'dark:hover:text-red-500',
    'dark:hover:text-red-600',
    'dark:hover:text-red-700',
    'dark:hover:text-red-800',
    'dark:hover:text-red-900',
    'dark:hover:text-teal-100',
    'dark:hover:text-teal-200',
    'dark:hover:text-teal-300',
    'dark:hover:text-teal-400',
    'dark:hover:text-teal-500',
    'dark:hover:text-teal-600',
    'dark:hover:text-teal-700',
    'dark:hover:text-teal-800',
    'dark:hover:text-teal-900',
    'dark:hover:text-transparent',
    'dark:hover:text-white',
    'dark:hover:text-yellow-100',
    'dark:hover:text-yellow-200',
    'dark:hover:text-yellow-300',
    'dark:hover:text-yellow-400',
    'dark:hover:text-yellow-50',
    'dark:hover:text-yellow-500',
    'dark:hover:text-yellow-600',
    'dark:hover:text-yellow-700',
    'dark:hover:text-yellow-800',
    'dark:hover:text-yellow-900',
    'dark:text-black',
    'dark:text-blue-100',
    'dark:text-blue-200',
    'dark:text-blue-300',
    'dark:text-blue-400',
    'dark:text-blue-50',
    'dark:text-blue-500',
    'dark:text-blue-600',
    'dark:text-blue-700',
    'dark:text-blue-800',
    'dark:text-blue-900',
    'dark:text-current',
    'dark:text-gray-100',
    'dark:text-gray-200',
    'dark:text-gray-300',
    'dark:text-gray-400',
    'dark:text-gray-50',
    'dark:text-gray-500',
    'dark:text-gray-600',
    'dark:text-gray-700',
    'dark:text-gray-800',
    'dark:text-gray-900',
    'dark:text-green-100',
    'dark:text-green-200',
    'dark:text-green-300',
    'dark:text-green-400',
    'dark:text-green-50',
    'dark:text-green-500',
    'dark:text-green-600',
    'dark:text-green-700',
    'dark:text-green-800',
    'dark:text-green-900',
    'dark:text-indigo-100',
    'dark:text-indigo-200',
    'dark:text-indigo-300',
    'dark:text-indigo-400',
    'dark:text-indigo-50',
    'dark:text-indigo-500',
    'dark:text-indigo-600',
    'dark:text-indigo-700',
    'dark:text-indigo-800',
    'dark:text-indigo-900',
    'dark:text-opacity-10',
    'dark:text-orange-100',
    'dark:text-orange-200',
    'dark:text-orange-300',
    'dark:text-orange-400',
    'dark:text-orange-500',
    'dark:text-orange-600',
    'dark:text-orange-700',
    'dark:text-orange-800',
    'dark:text-orange-900',
    'dark:text-pink-100',
    'dark:text-pink-200',
    'dark:text-pink-300',
    'dark:text-pink-400',
    'dark:text-pink-50',
    'dark:text-pink-500',
    'dark:text-pink-600',
    'dark:text-pink-700',
    'dark:text-pink-800',
    'dark:text-pink-900',
    'dark:text-purple-100',
    'dark:text-purple-200',
    'dark:text-purple-300',
    'dark:text-purple-400',
    'dark:text-purple-50',
    'dark:text-purple-500',
    'dark:text-purple-600',
    'dark:text-purple-700',
    'dark:text-purple-800',
    'dark:text-purple-900',
    'dark:text-red-100',
    'dark:text-red-200',
    'dark:text-red-300',
    'dark:text-red-400',
    'dark:text-red-50',
    'dark:text-red-500',
    'dark:text-red-600',
    'dark:text-red-700',
    'dark:text-red-800',
    'dark:text-red-900',
    'dark:text-teal-100',
    'dark:text-teal-200',
    'dark:text-teal-300',
    'dark:text-teal-400',
    'dark:text-teal-500',
    'dark:text-teal-600',
    'dark:text-teal-700',
    'dark:text-teal-800',
    'dark:text-teal-900',
    'dark:text-transparent',
    'dark:text-white',
    'dark:text-yellow-100',
    'dark:text-yellow-200',
    'dark:text-yellow-300',
    'dark:text-yellow-400',
    'dark:text-yellow-50',
    'dark:text-yellow-500',
    'dark:text-yellow-600',
    'dark:text-yellow-700',
    'dark:text-yellow-800',
    'dark:text-yellow-900',
    'hover:bg-black',
    'hover:bg-blue-100',
    'hover:bg-blue-200',
    'hover:bg-blue-300',
    'hover:bg-blue-400',
    'hover:bg-blue-500',
    'hover:bg-blue-600',
    'hover:bg-blue-700',
    'hover:bg-blue-800',
    'hover:bg-blue-900',
    'hover:bg-current',
    'hover:bg-gray-100',
    'hover:bg-gray-200',
    'hover:bg-gray-300',
    'hover:bg-gray-400',
    'hover:bg-gray-500',
    'hover:bg-gray-600',
    'hover:bg-gray-700',
    'hover:bg-gray-800',
    'hover:bg-gray-900',
    'hover:bg-green-100',
    'hover:bg-green-200',
    'hover:bg-green-300',
    'hover:bg-green-400',
    'hover:bg-green-500',
    'hover:bg-green-600',
    'hover:bg-green-700',
    'hover:bg-green-800',
    'hover:bg-green-900',
    'hover:bg-indigo-100',
    'hover:bg-indigo-200',
    'hover:bg-indigo-300',
    'hover:bg-indigo-400',
    'hover:bg-indigo-500',
    'hover:bg-indigo-600',
    'hover:bg-indigo-700',
    'hover:bg-indigo-800',
    'hover:bg-indigo-900',
    'hover:bg-orange-100',
    'hover:bg-orange-200',
    'hover:bg-orange-300',
    'hover:bg-orange-400',
    'hover:bg-orange-500',
    'hover:bg-orange-600',
    'hover:bg-orange-700',
    'hover:bg-orange-800',
    'hover:bg-orange-900',
    'hover:bg-pink-100',
    'hover:bg-pink-200',
    'hover:bg-pink-300',
    'hover:bg-pink-400',
    'hover:bg-pink-500',
    'hover:bg-pink-600',
    'hover:bg-pink-700',
    'hover:bg-pink-800',
    'hover:bg-pink-900',
    'hover:bg-purple-100',
    'hover:bg-purple-200',
    'hover:bg-purple-300',
    'hover:bg-purple-400',
    'hover:bg-purple-500',
    'hover:bg-purple-600',
    'hover:bg-purple-700',
    'hover:bg-purple-800',
    'hover:bg-purple-900',
    'hover:bg-red-100',
    'hover:bg-red-200',
    'hover:bg-red-300',
    'hover:bg-red-400',
    'hover:bg-red-500',
    'hover:bg-red-600',
    'hover:bg-red-700',
    'hover:bg-red-800',
    'hover:bg-red-900',
    'hover:bg-teal-100',
    'hover:bg-teal-200',
    'hover:bg-teal-300',
    'hover:bg-teal-400',
    'hover:bg-teal-500',
    'hover:bg-teal-600',
    'hover:bg-teal-700',
    'hover:bg-teal-800',
    'hover:bg-teal-900',
    'hover:bg-transparent',
    'hover:bg-white',
    'hover:bg-yellow-100',
    'hover:bg-yellow-200',
    'hover:bg-yellow-300',
    'hover:bg-yellow-400',
    'hover:bg-yellow-500',
    'hover:bg-yellow-600',
    'hover:bg-yellow-700',
    'hover:bg-yellow-800',
    'hover:bg-yellow-900',
    'hover:text-black',
    'hover:text-blue-100',
    'hover:text-blue-200',
    'hover:text-blue-300',
    'hover:text-blue-400',
    'hover:text-blue-50',
    'hover:text-blue-500',
    'hover:text-blue-600',
    'hover:text-blue-700',
    'hover:text-blue-800',
    'hover:text-blue-900',
    'hover:text-current',
    'hover:text-gray-100',
    'hover:text-gray-200',
    'hover:text-gray-300',
    'hover:text-gray-400',
    'hover:text-gray-50',
    'hover:text-gray-500',
    'hover:text-gray-600',
    'hover:text-gray-700',
    'hover:text-gray-800',
    'hover:text-gray-900',
    'hover:text-green-100',
    'hover:text-green-200',
    'hover:text-green-300',
    'hover:text-green-400',
    'hover:text-green-50',
    'hover:text-green-500',
    'hover:text-green-600',
    'hover:text-green-700',
    'hover:text-green-800',
    'hover:text-green-900',
    'hover:text-indigo-100',
    'hover:text-indigo-200',
    'hover:text-indigo-300',
    'hover:text-indigo-400',
    'hover:text-indigo-50',
    'hover:text-indigo-500',
    'hover:text-indigo-600',
    'hover:text-indigo-700',
    'hover:text-indigo-800',
    'hover:text-indigo-900',
    'hover:text-opacity-10',
    'hover:text-orange-100',
    'hover:text-orange-200',
    'hover:text-orange-300',
    'hover:text-orange-400',
    'hover:text-orange-500',
    'hover:text-orange-600',
    'hover:text-orange-700',
    'hover:text-orange-800',
    'hover:text-orange-900',
    'hover:text-pink-100',
    'hover:text-pink-200',
    'hover:text-pink-300',
    'hover:text-pink-400',
    'hover:text-pink-50',
    'hover:text-pink-500',
    'hover:text-pink-600',
    'hover:text-pink-700',
    'hover:text-pink-800',
    'hover:text-pink-900',
    'hover:text-purple-100',
    'hover:text-purple-200',
    'hover:text-purple-300',
    'hover:text-purple-400',
    'hover:text-purple-50',
    'hover:text-purple-500',
    'hover:text-purple-600',
    'hover:text-purple-700',
    'hover:text-purple-800',
    'hover:text-purple-900',
    'hover:text-red-100',
    'hover:text-red-200',
    'hover:text-red-300',
    'hover:text-red-400',
    'hover:text-red-50',
    'hover:text-red-500',
    'hover:text-red-600',
    'hover:text-red-700',
    'hover:text-red-800',
    'hover:text-red-900',
    'hover:text-teal-100',
    'hover:text-teal-200',
    'hover:text-teal-300',
    'hover:text-teal-400',
    'hover:text-teal-500',
    'hover:text-teal-600',
    'hover:text-teal-700',
    'hover:text-teal-800',
    'hover:text-teal-900',
    'hover:text-transparent',
    'hover:text-white',
    'hover:text-yellow-100',
    'hover:text-yellow-200',
    'hover:text-yellow-300',
    'hover:text-yellow-400',
    'hover:text-yellow-50',
    'hover:text-yellow-500',
    'hover:text-yellow-600',
    'hover:text-yellow-700',
    'hover:text-yellow-800',
    'hover:text-yellow-900',
    'text-black',
    'text-blue-100',
    'text-blue-200',
    'text-blue-300',
    'text-blue-400',
    'text-blue-50',
    'text-blue-500',
    'text-blue-600',
    'text-blue-700',
    'text-blue-800',
    'text-blue-900',
    'text-current',
    'text-gray-100',
    'text-gray-200',
    'text-gray-300',
    'text-gray-400',
    'text-gray-50',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-gray-900',
    'text-green-100',
    'text-green-200',
    'text-green-300',
    'text-green-400',
    'text-green-50',
    'text-green-500',
    'text-green-600',
    'text-green-700',
    'text-green-800',
    'text-green-900',
    'text-indigo-100',
    'text-indigo-200',
    'text-indigo-300',
    'text-indigo-400',
    'text-indigo-50',
    'text-indigo-500',
    'text-indigo-600',
    'text-indigo-700',
    'text-indigo-800',
    'text-indigo-900',
    'text-opacity-10',
    'text-orange-100',
    'text-orange-200',
    'text-orange-300',
    'text-orange-400',
    'text-orange-500',
    'text-orange-600',
    'text-orange-700',
    'text-orange-800',
    'text-orange-900',
    'text-pink-100',
    'text-pink-200',
    'text-pink-300',
    'text-pink-400',
    'text-pink-50',
    'text-pink-500',
    'text-pink-600',
    'text-pink-700',
    'text-pink-800',
    'text-pink-900',
    'text-purple-100',
    'text-purple-200',
    'text-purple-300',
    'text-purple-400',
    'text-purple-50',
    'text-purple-500',
    'text-purple-600',
    'text-purple-700',
    'text-purple-800',
    'text-purple-900',
    'text-red-100',
    'text-red-200',
    'text-red-300',
    'text-red-400',
    'text-red-50',
    'text-red-500',
    'text-red-600',
    'text-red-700',
    'text-red-800',
    'text-red-900',
    'text-teal-100',
    'text-teal-200',
    'text-teal-300',
    'text-teal-400',
    'text-teal-500',
    'text-teal-600',
    'text-teal-700',
    'text-teal-800',
    'text-teal-900',
    'text-transparent',
    'text-white',
    'text-yellow-100',
    'text-yellow-200',
    'text-yellow-300',
    'text-yellow-400',
    'text-yellow-50',
    'text-yellow-500',
    'text-yellow-600',
    'text-yellow-700',
    'text-yellow-800',
    'text-yellow-900',
    'btn-facebook',
    'btn-twitter',
    'btn-tumblr',
    'btn-reddit',
    'btn-google',
    'btn-linkedin',
    'btn-email',
    'btn-whatsapp',
    'btn-vk',
    'btn-telegram',
  ],
  theme: {
    extend: {
      maxWidth: {
        '8xl': '90rem',
      },
      spacing: {
        '9/16': '56.25%',
      },
      lineHeight: {
        11: '2.75rem',
        12: '3rem',
        13: '3.25rem',
        14: '3.5rem',
      },
      fontFamily: {
        sans: ['IBM Plex Mono', ...defaultTheme.fontFamily.sans],
      },
      colors: {
        primary: colors.blue,
        gray: colors.neutral,
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            color: theme('colors.gray.700'),
            a: {
              color: theme('colors.primary.500'),
              '&:hover': {
                color: `${theme('colors.primary.600')} !important`,
              },
              code: { color: theme('colors.primary.400') },
            },
            h1: {
              fontWeight: '700',
              letterSpacing: theme('letterSpacing.tight'),
              color: theme('colors.gray.900'),
            },
            h2: {
              fontWeight: '700',
              letterSpacing: theme('letterSpacing.tight'),
              color: theme('colors.gray.900'),
            },
            h3: {
              fontWeight: '600',
              color: theme('colors.gray.900'),
            },
            'h4,h5,h6': {
              color: theme('colors.gray.900'),
            },
            pre: {
              backgroundColor: theme('colors.gray.800'),
            },
            code: {
              color: theme('colors.pink.500'),
              backgroundColor: theme('colors.gray.100'),
              paddingLeft: '4px',
              paddingRight: '4px',
              paddingTop: '2px',
              paddingBottom: '2px',
              borderRadius: '0.25rem',
            },
            'code::before': {
              content: 'none',
            },
            'code::after': {
              content: 'none',
            },
            details: {
              backgroundColor: theme('colors.gray.100'),
              paddingLeft: '4px',
              paddingRight: '4px',
              paddingTop: '2px',
              paddingBottom: '2px',
              borderRadius: '0.25rem',
            },
            hr: { borderColor: theme('colors.gray.200') },
            'ol li::marker': {
              fontWeight: '600',
              color: theme('colors.gray.500'),
            },
            'ul li::marker': {
              backgroundColor: theme('colors.gray.500'),
            },
            strong: { color: theme('colors.gray.600') },
            blockquote: {
              color: theme('colors.gray.900'),
              borderLeftColor: theme('colors.gray.200'),
            },
          },
        },
        dark: {
          css: {
            color: theme('colors.gray.300'),
            a: {
              color: theme('colors.primary.500'),
              '&:hover': {
                color: `${theme('colors.primary.400')} !important`,
              },
              code: { color: theme('colors.primary.400') },
            },
            h1: {
              fontWeight: '700',
              letterSpacing: theme('letterSpacing.tight'),
              color: theme('colors.gray.100'),
            },
            h2: {
              fontWeight: '700',
              letterSpacing: theme('letterSpacing.tight'),
              color: theme('colors.gray.100'),
            },
            h3: {
              fontWeight: '600',
              color: theme('colors.gray.100'),
            },
            'h4,h5,h6': {
              color: theme('colors.gray.100'),
            },
            pre: {
              backgroundColor: theme('colors.gray.800'),
            },
            code: {
              backgroundColor: theme('colors.gray.800'),
            },
            details: {
              backgroundColor: theme('colors.gray.800'),
            },
            hr: { borderColor: theme('colors.gray.700') },
            'ol li::marker': {
              fontWeight: '600',
              color: theme('colors.gray.400'),
            },
            'ul li::marker': {
              backgroundColor: theme('colors.gray.400'),
            },
            strong: { color: theme('colors.gray.100') },
            thead: {
              th: {
                color: theme('colors.gray.100'),
              },
            },
            tbody: {
              tr: {
                borderBottomColor: theme('colors.gray.700'),
              },
            },
            blockquote: {
              color: theme('colors.gray.100'),
              borderLeftColor: theme('colors.gray.700'),
            },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
}
