version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  clean:
    desc: Clean
    cmds:
      - rm public/{sitemap.xml,robots.txt,feed.rss}
      - rm -r dist
    ignore_error: true

  prebuild:
    desc: Prebuild
    cmds:
      - task: clean
      - touch public/{sitemap.xml,robots.txt,feed.rss}
    ignore_error: true

  build:
    desc: Build
    cmds:
      - task: install
      - task: prebuild
      - pnpm run build

  update_dep:
    desc: Check whether the new version of the npm package broke the build.
    cmds:
      - git switch main
      - git pull origin main
      - git switch deps/{{.CLI_ARGS}} 2>/dev/null || git switch -c deps/{{.CLI_ARGS}}
      - ncu -u -f {{.CLI_ARGS}}
      - task: install
      - task: build
      - git add package.json pnpm-lock.yaml
    silent: true
  update_deps:
    desc: Check whether the new version of the npm packages broke the build.
    cmds:
      - git switch main
      - git pull origin main
      - git switch deps/upgrade 2>/dev/null || git switch -c deps/upgrade
      - ncu -u -f {{.CLI_ARGS}}
      - task: install
      - task: build
      - git add package.json pnpm-lock.yaml
    silent: true
