version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  clean:
    desc: Clean
    cmds:
      - rm public/{sitemap.xml,robots.txt,feed.rss}
      - rm -r dist
    ignore_error: true

  prebuild:
    desc: Prebuild
    cmds:
      - task: clean
      - touch public/{sitemap.xml,robots.txt,feed.rss}
    ignore_error: true

  build:
    desc: Build
    cmds:
      - task: install
      - task: prebuild
      - pnpm run build

  posts:
    desc: List post files
    cmds:
      - ls src/pages/posts | grep \.md$ | sed 's/\.md$//' | grep {{.CLI_ARGS}}

  md2html:
    desc: Generate HTML from markdown
    cmds:
      - mkdir .medium || true
      - echo "Generating HTML..."
      - md2html -o .medium/{{.CLI_ARGS}}.html src/pages/posts/{{.CLI_ARGS}}.md
      - echo "Done."
    silent: true

  post2md:
    desc: Create draft post on Medium
    cmds:
      - echo "Posting a draft post to Medium..."
      - md-publisher publish .medium/{{.CLI_ARGS}}.html
      - echo "Done."
    silent: true

  update_dep:
    desc: Check whether the new version of the npm package broke the build.
    cmds:
      - git switch main
      - git pull origin main
      - git switch deps/{{.CLI_ARGS}} 2>/dev/null || git switch -c deps/{{.CLI_ARGS}}
      - ncu -u -f {{.CLI_ARGS}}
      - task: install
      - task: build
      - git add package.json pnpm-lock.yaml
    silent: true

  update_deps:
    desc: Check whether the new version of the npm packages broke the build.
    cmds:
      - git switch main
      - git pull origin main
      - git switch deps/upgrade 2>/dev/null || git switch -c deps/upgrade
      - ncu -u -f {{.CLI_ARGS}}
      - task: install
      - task: build
      - git add package.json pnpm-lock.yaml
    silent: true
