version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  clean:
    desc: Clean
    cmds:
      - rm public/{sitemap.xml,robots.txt,feed.rss}
      - rm -r dist
    ignore_error: true

  prebuild:
    desc: Prebuild
    cmds:
      - task: clean
      - touch public/{sitemap.xml,robots.txt,feed.rss}
    ignore_error: true

  build:
    desc: Build
    cmds:
      - task: install
      - task: prebuild
      - pnpm run build

  test_update:
    desc: Check whether the new version of the npm package broke the build.
    cmds:
      - git checkout main
      - git checkout -b deps/{{.CLI_ARGS}}
      - ncu -u -f {{.CLI_ARGS}}
      - task: install
      - task: build
    silent: true
